### ISSUE TITLE
about robot walk higher

### ISSUE THREAD

**Issue by xiaof0205** [SimarKareer/ViNL#6]
Hello, I would like to ask you, how do you fine-tune the strategy to make the robot walk higher? Looking forward to your reply

**Comment by SimarKareer** [comment]
Hi @xiaof0205, mind explaining a bit more what you mean by "the robot walk higher."  Under the readme I've included a section titled "Full Training Procedure".  Stage 2 of training is when the robot starts to learn to step over obstacles, which is what I think you might be referring to.  Let me know if this helps!
